version: '3.8'
services:
  postgres:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=u4crypto
      - POSTGRES_PASSWORD=u4crypto
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
